### ISSUE TITLE
Delete Addresses

### ISSUE THREAD

**Issue by benaduggan** [Tiny-Hands/tinyhands#158]
# Address Management Deletion Endpoints
#### A User wants to be able to safely delete an Address

This story will involve updating the Address serializers and creating a new delete endpoint. 

###### DELETE /api/address1/:id/
These Delete endpoints will check for related items, and if there are no related items, it will delete the address. Otherwise it should respond with an exception

###### GET /api/address2/:id/related-items
Returns the information below

##### Serializers
create new Serializers that inherit from the normal one, but extend it to offer the related items structure as a new field
```
{
    "id": 785,
    "related_items": [
        {
            "type": "address2",
            "ids": []
        },
        {
            "type": "person",
            "ids": [
                3501
            ]
        },
        {
            "type": "victiminterview",
            "ids": []
        },
        {
            "type": "victiminterviewlocationbox",
            "ids": []
        }
    ],
    "name": "Aaron",
    "latitude": 40.0,
    "longitude": 40.0,
    "level": "District",
    "completed": false
}
```

**Comment by andrew-smith3** [comment]
Deployed to Production
