### ISSUE TITLE
Alert permission needs to be split into two permissions

### ISSUE THREAD

**Issue by benaduggan** [Tiny-Hands/tinyhands#191]
## Alert permission needs to be split into two permissions

Right now there is one permission for alerts, people either receive email alerts or they do not. We want there to be sub-settings for Legal Alerts and for Investigation Alerts so people only receive the alerts they need to know about. 
### The current requirements
- Alerts should be broken into two different options: Legal and Investigations. 
- The Legal e-mail should start with "Attention: Case Coordinator" instead of "Attention: Case Manager".
### Ben's Technical Analysis:
- Update the Account and DefaultPermissionsSet models to breakout the permission into two permissions. One for Investigation Alerts and one for Legal Alerts
- Add a type field to the Alert model to distinguish between legal and investigations alerts - below are the current alerts and what their types should be
  - Legal Alerts: 
    - 'fir_and_dofe_against'
    - 'ten_or_more_case_points'
  - Investigation Alerts: 
    - 'Identified Trafficker'
    - 'trafficker_name_match'
- Change the way the sending email logic works (eg. If someone has the legal alert permission, they should receive alerts with the type: legal)
- Update the templated emails that have "Attention: Case Manager" to "Attention: Case Coordinator"

**Comment by jahudlow** [comment]
Each alert has been coming with the corresponding title and first line, but the main issue has been not having separate options for them in Access Control. I believe the criteria for Legal Alerts were to either have 10 or more Strength of Case points or for a legal case to have been filed (both from VIF), and for Investigations Alerts it was a trafficker name match with 90% or higher certainty (from IRF). 
We don't currently have plans for other types of alerts, but would like to keep the criteria for these flexible so we can adjust them based on how well they're working.

**Comment by jahudlow** [comment]
Not sure whether or not you guys can see the alerts as they have been coming, so here are two examples:
![legal alert](https://cloud.githubusercontent.com/assets/14357347/19485468/7c2fbdca-9585-11e6-8833-aab3f1ebf3fa.jpg)
![investigations alert](https://cloud.githubusercontent.com/assets/14357347/19485470/7e09de1e-9585-11e6-8de5-0e56b6db2c4e.jpg)
