### ISSUE TITLE
`Save for later` leads to old page.

### ISSUE THREAD

**Issue by jsouthwo** [Tiny-Hands/tinyhands#195]
This bug is currently on staging. To reproduce:

1. Start creating an new IRF.
2. Enter a few fields.
3. Click the `Save for later` button.
3. This takes you to https://staging.tinyhandsdreamsuite.org/data-entry/irfs/ rather than https://staging.tinyhandsdreamsuite.org/#/irf
4. This page includes outdated links, (clicking `Budget Sheets` in the navbar leads to a 404).

**Comment by benaduggan** [comment]
Closed by #194 

I redeployed staging with the change.
