### ISSUE TITLE
When creating events, there is no visual feedback for the error that is caught when making a repeating event end on the original end date.

### ISSUE THREAD

**Issue by jsouthwo** [Tiny-Hands/tinyhands#199]
Still does not appear to be working on staging.

[Trello card.](https://trello.com/c/y7xdE1D5/100-when-creating-events-there-is-no-visual-feedback-for-the-error-that-is-caught-when-making-a-repeating-event-end-on-the-original-)

**Comment by benaduggan** [comment]
Closed and moved to Client as an issue
