### ISSUE TITLE
Monthly Reports

### ISSUE THREAD

**Issue by amunn33** [Tiny-Hands/tinyhands#200]
New data entry for forms that are submitted by border stations monthly to report on their effectiveness for the month and their costs.

[New_Monthly_Report_(for_THN).docx](https://github.com/Tiny-Hands/tinyhands/files/517867/New_Monthly_Report_.for_THN.docx)

Very big addition, but I just want to have the document on here so we don't lost track of it.

**Comment by benaduggan** [comment]
Closed because Justin opened another issue for this.
