### ISSUE TITLE
Mutually exclusive field values modeled incorrectly

### ISSUE THREAD

**Issue by jsouthwo** [Tiny-Hands/tinyhands#203]
The IRF and (especially) VIF include numerous fields that are mutually exclusive. For example, only one "Occupation" can be selected at a time on the VIF. However, in the data model, there is a Boolean field for each of the possible values. Refactor as follows:
- Model should have a single "choices" field for all mutually exclusive values on the form.
- Form should employ radio buttons (or a dropdown list?) to indicate mutually-exclusive choices.

This change will significantly reduce the size of the tables that back the IRF and VIF.

[Trello card.](https://trello.com/c/T6rGnchR/58-mutually-exclusive-field-values-modeled-incorrectly)

**Comment by andrew-smith3** [comment]
This issue will be made irrelevant with our changes to the data model. I think we will leave it for now and deal with it once we have a clear path forward for the data model.
