### ISSUE TITLE
BCW Questions / Change Requests from Kirk

### ISSUE THREAD

**Issue by jahudlow** [Tiny-Hands/tinyhands#209]
Hey guys, couple comments about the BCW on the DS. I filled out two forms, but then decided to just do the paper copies this month. The main things are I just need to know that I can download and print it with a good format. I also really need the point about the medical expenses to be fixed before I can start using it. Thanks!

- [x] We need to fix re-populating the budget sheet with last month's data
- [x] There are two places that depend on the # of INTs (last month's total): stationary amount in the Admin section and food amount in the Food & Gas section. Would it be possible to have a spot a that the very beginning that you can just enter the # of INTs from the last month and it will automatically calculate for those two parts? [note from Jon: I think the intention was also to have the number of intercepts from the previous month update automatically based on the interceptee count for that station, but it is broken right now]
- [x] Is there an easy way to print the BCW? I also clicked on the "Resend MDF" and it looks like the formatting is pretty off… It would be great if the printed version would look something as close as possible to the Monthly Distribution Worksheet (see attached) (all on one page ideally).
- [x] Medical - I need to be able to add separate line items for different medical expenses. In addition to those things, how hard would it be to be able to "add an item" in the Admin section (like the other sections)?

[Monthly Distribution (Bhadrapur) - Aug16.docx](https://github.com/Tiny-Hands/tinyhands/files/545530/Monthly.Distribution.Bhadrapur.-.Aug16.docx)

**Comment by benaduggan** [comment]
@jahudlow I had a couple questions:

Thinking back to the original budget sheet implementation. Didn't we want essentially a copy of the previous month's budget sheet pre-populated into a new budget sheet when it was created? Would he prefer that functionality over just having recurring items appear?

What would he like the printable version of the BCW to look like?

**Comment by jahudlow** [comment]
Here is Kirk's response:

I think, yes, pre-populating the sheet with last month's data should be fine and solve the issue of "recurring items."

I would like the printable version of the BCW to look something very close to the attached Monthly Distribution Worksheet. I currently have the create both BCWs and MDWs. If I can just do the BCW and then click print and get something relatively similar to the example MDW, that would be awesome!
[Monthly Distribution (Bhadrapur) - Oct16.docx](https://github.com/Tiny-Hands/tinyhands/files/558052/Monthly.Distribution.Bhadrapur.-.Oct16.docx)

**Comment by andrewfennig** [comment]
What is wrong with the automated Money Distribution Form? Doesn't it look pretty much like the one Kirk attached?

**Comment by jahudlow** [comment]
Sorry for my delay on this. The MDF is mostly fine, but in some cases it's going onto a second page when the right side of the first page is still mostly empty. It may have to do with how it's set up to deal with extra Misc items that don't fit at the bottom of the left column on the first page (see example attached). Once the "Medical" section is set up to allow for adding items then we'll want to be sure each item also appears on the MDF as well.
[Monthly-Money-Distribution-Form.pdf](https://github.com/Tiny-Hands/tinyhands/files/566175/Monthly-Money-Distribution-Form.pdf)

**Comment by amunn33** [comment]
These should all have been implemented.
