### ISSUE TITLE
Add Delete Capability for Address 1s and 2s

### ISSUE THREAD

**Issue by jahudlow** [Tiny-Hands/tinyhands#216]
Currently we're unable to delete Address 1s or Address 2s. One problem this is causing is that when a duplicate address is added by mistake a Sever Error 500 is generated when someone attempts to use the duplicated address. The address 2 can't be deleted or modified to a new and different address. Some sort of warning message when a user tries to create an address which already exists (but with a different level) would also solve this problem. A current example of this is "Pang, Parbat" which was created as a VDC and a City.

**Comment by benaduggan** [comment]
I'm closing this issue because the backend has this feature implemented, we are just waiting on the frontend issue [here](https://github.com/Tiny-Hands/tinyhands-client/issues/66)
