### ISSUE TITLE
Year to date Interceptions

### ISSUE THREAD

**Issue by andrewfennig** [Tiny-Hands/tinyhands#226]
In the details view when you hover over a borders station flag, let's show the Year To Date number of intercepts (YTD) in addition to the total number of intercepts for that station. Can we show the cumulative YTD numbers somewhere on the dashboard??

**Comment by benaduggan** [comment]
## Technical Details for the backend

This should be a simple calculation that we can add directly to the border station serializer. We already have a couple of simple calculations being done [here](https://github.com/Tiny-Hands/tinyhands/blob/develop/application/dataentry/serializers.py#L77) so we can follow the same pattern.

[Front end issue](https://github.com/Tiny-Hands/tinyhands-client/issues/106)

**Comment by benaduggan** [comment]
@andrewfennig @jahudlow 

What is the requirement for an intercept? Is that an IRF? or each individual interceptee?

**Comment by amunn33** [comment]
Sorry I missed this, an intercept should actually just be counting victim interceptees.
