### ISSUE TITLE
Budget Calculations - New budget sheet - previous data endpoint

### ISSUE THREAD

**Issue by benaduggan** [Tiny-Hands/tinyhands#239]
# The Story

As a user entering a budget form, I would like to specify the date I am submitting the form for and see the previous months budget form loaded 

The idea here being that the budgets do not change significantly from month to month, so it is easier to have one pre-filled with the last one and modified instead of starting from scratch. 

# Requirements

We want an endpoint that when given a month, year, and border station Id, returns the content of the last budget calculation sheet submitted before that month for that border station, but also the top table information should be calculated for the given month and year

So if I give you June 2016, I would expect you to return May 2016s budget calculation. but Junes calculations for the top table.

IF May 2016's budget doesn't exist, I think we want to get the information of the next most recent budget sheet. @kirkschweitzer01 Do you have an opinion on that? 

# Technical Details
Currently we have the following two endpoints that don't really do what I want them to do.

```
retrieve_latest_budget_sheet_for_border_station: budget/most_recent_form/(?P<pk>\d+)/
previous_data: budget/previous_data/(?P<pk>\d+)/(?P<month>\d+)/(?P<year>\d+)/$
```

The `previous_data` method only provides the information for the top table of the budget form for a given month and year, but not the form for to pre-load the fields, and the `retrieve_latest_budget_sheet_for_border_station` method only gives you the latest form that has been created, not since a certain date. 

So I think I want you to delete both of those endpoints, and create a new one like this:
`GET - /budget/(?P<pk>\d+)/template/(?P<month>\d+)/(?P<year>\d+)/$`

(I'm not sure if I like the word "template" in that url, so if you come up with a better one, feel free to change it. I'm trying to be a pragmatic api designer, but I'm not exactly sure what that means sometimes :stuck_out_tongue:)

Your new endpoint will both calculate the same data from the `previous_data` method for the top table for the passed in month and year, and also get the content of the form previously submitted for the border station from the specified date (including staff salaries, and other items linked to that form). It would also be helpful for the front end if you set the month_year field to be for the date passed 

I don't really have a structure in mind right now, but probably something like this: 
```
{
     "topTableData": {previous_data stuff}.
     "form": {the form},
     "staff_salaries": [staff salaries from form],
     "other_items": [other items from form]
}
```

@kirkschweitzer01 Let us know if anything here doesn't sound right to you!

**Comment by kirkschweitzer01** [comment]
Yes, I agree. There shouldn't ever be a case like you suggested (when one month is missing, but there is a budget for an early month). But if that ever did happen, I think that would be a good default.

**Comment by Adam7700** [comment]
@benaduggan Do you know what the frontend will be expecting if there are no budget sheets before the given date? Right now I just return the same hash with the values as None

**Comment by benaduggan** [comment]
@Adam7700 I think I'm going to do some major refactoring on the front end so I could make that work. It might be easier to work with 0s instead of Nones though if that's easy to do on your end!

**Comment by Adam7700** [comment]
No problem. I was also going to return the data in the format of:
 ```
{'top_level_data': stuff, 
 'previous_budget_data': {
        'other_items': stuff,
        'staff_salaries': stuff,
        'budget_form': stuff
 }
}
```

Let me know if that works or if you'd like something different. Wont be hard to change.

**Comment by benaduggan** [comment]
Looks great!

**Comment by amunn33** [comment]
1. I should have caught this earlier but in budget_views, the "gte" fields used for getting victim interceptee counts are the time of interception instead of time entered into system.

2. I'm not sure why but the forms are not being retrieved on staging for Bhairawa (station id 1). It will retrieve successfully if you go to a month that already has a form entered but errors on any others. None of the other stations that I tested had the same issue and I couldn't get the problem replicated locally.

**Comment by benaduggan** [comment]
1. okay, that should be quick change

2. I found the underlying issue. There was a staff salary that had a blank value which caused [this function](https://github.com/Tiny-Hands/tinyhands/blob/develop/application/budget/models.py#L237) to bork out when it tried to add None and an integer.  I think the change should probably be to add some protections around entering in null values. we should probably say null is equivalent to 0 when storing the data, and also disable the save button on budget if there are staff without salaries

**Comment by amunn33** [comment]
So it looks like the previous salaries are not actually getting populated through this setup. Phil just went through and did all of last months budget sheets and said none of the salaries from last month's sheets were populated. I haven't checked to see if it is an issue on the server side (salaries aren't actually getting sent to the client) or if the client just isn't displaying the information.

**Comment by amunn33** [comment]
This is addressed in client issue 175
