### ISSUE TITLE
Add Country Model

### ISSUE THREAD

**Issue by amunn33** [Tiny-Hands/tinyhands#256]
# Goal
Create operating country model that will be used in border station model

# Requirements
- Country model should include [name, latitude, longitude, and zoom level] (zoom level will be used later for the dashboard)
- Border Station model should include an "operating country" that will be a foreign key to country
- Add Border Station field to IRF and VIF models

**Comment by Adam7700** [comment]
Couple questions:
1. Could you explain zoom level a little more? Im not sure what datatype to make that without knowing what its being used for ;)

2. When you say add border station field to irv and vif, im assuming you mean a border station id foriegn key?

Thanks!

**Comment by amunn33** [comment]
1) Sorry about that, the zoom field is not extremely necessary right now, it is what controls how far in the map should be zoomed in on the dashboard. It will just be an integer.. if you check out this file in the client you can see that we currently just have it hard coded, along with the lat and long, to be set for Nepal's needs. https://github.com/Tiny-Hands/tinyhands-client/blob/develop/src/app/dashboard/map/map.html

2) Yes it will just be a foreign field
