### ISSUE TITLE
Change MDF email recipient options

### ISSUE THREAD

**Issue by amunn33** [Tiny-Hands/tinyhands#266]
# Story

Person A, B, and C are currently selected as "Receives MDF" on their border station's page. When the user goes to send out this month's MDF, a list of all staff and committee members from their station is displayed with Person A, B, and C selected to be sent this month's MDF. The user decides that Person D should receive this month's MDF and that Person B should not, so they make those changes and sends out the MDF. Next month, when the user goes to send out the MDF, their changes are still reflected and Person A, C, and D are the ones selected by default.

# Background

The current way of selecting who receives MDFs is a little bit over-complicated. You choose who should receive it on the border station page and when you go to send it, a list of only those people pops up and allows you to deselect them before sending if you would like. The problem with this is that your last second changes are not saved so if you would want to remove somebody from that list, you have to go back into the border station page. It also requires that if you want to add somebody new to the list that you go to the border station page. Kirk suggested that it would be more helpful if the user could see everyone from that border station and choose to add them/remove them from the receiving list from the MDF sending page. In doing this, the expectation is also that changes made on this page would be reflected on the border station page. 

# Requirements

Show all staff and committee members on the "Resend MDF" page regardless of their status of receiving the MDF.*
All changes made on the "Resend MDF" page to a person's status should be reflected in their person record.

*Do not display any staff or committee members if they do not have an email

**Comment by andrew-smith3** [comment]
This looks good. In testing it out I did notice some things we will want to improve that were existing before. 
 - If no recipient is checked on the mdf form, we should disable the send button. Hitting it with no recipients causes no harm but I think we should still disable it.
 - The check box to receive an mdf on the Border Station page should be disabled if no email is present. Again, doesn't cause any harm now but would still be good to implement.
