### ISSUE TITLE
Disable Border Station "Recieves Money Distribution Form" checkbox when no email is provided

### ISSUE THREAD

**Issue by andrew-smith3** [Tiny-Hands/tinyhands#274]
On the BorderStation page, the "Recieves Money Distribution Form" checkbox next to Staff and Committee Members should not be checked when a valid email for the staff or committee member is not available.

**Comment by benaduggan** [comment]
This is a front end issue, so the issues has been moved into [this issue](https://github.com/Tiny-Hands/tinyhands-client/issues/135)
