### ISSUE TITLE
Permissions Failing when operating country was NULL

### ISSUE THREAD

**Issue by benaduggan** [Tiny-Hands/tinyhands#410]
@scrishel I'm not sure if this is a situation where we just forgot to load in the border-station's country and it wont happen again, but we've been getting lots of failures because the following line 500s if the operating country is null

https://github.com/Tiny-Hands/tinyhands/blob/master/application/budget/views/money_distribution_views.py#L39

I made a quick fix by setting all the border stations to Nepal since that's the only one we have, but we probably want a better plan for the future

**Comment by scrishel** [comment]
We discussed that the operating country needed to be populated in existing border stations in one of our weekly meetings.  I thought that @amunn33 was going to set them in the production.  The updated logic to create a new border station requires the operating country to be specified.

**Comment by benaduggan** [comment]
Where is that logic located?

**Comment by benaduggan** [comment]
okay, yeah. What do you think about just changing the model to not allow null or blank? That should automatically make the serializer behave how we want it to

**Comment by scrishel** [comment]
Changing the model should be fine.  Just need to make sure we set the country for all stations in staging and production before migrating.

**Comment by benaduggan** [comment]
Yeah, and it might be good to update our sanitized data here sometime now
that we've been changing so much stuff lately.
